package com.example.tasksManagement.task.taskEnum;

public enum TaskType {
    ORGANIZE_TEAM_MEETING,
    CREATE_MONTHLY_REPORT,
    PREPARE_CLIENT_PRESENTATION,
    DEVELOP_MARKETING_PLAN,
    PREPARE_COMPETITIVE_ANALYSIS
}
